name: medlib
version: "0.1.0"
extra-source-files:
- README.md

# all unintrusive extensions from Alexis King's 2018 recommended defaults
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
# plus TypeApplications (useful even without ScopedTypeVariables)
default-extensions:
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- LambdaCase
- DeriveGeneric
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- BangPatterns
- KindSignatures
- TypeOperators
- TypeApplications

dependencies:
- base
- bytestring
- mtl
- lens
- stm
- stm-chans
- async
- directory
- containers
- text
- filepath
- typed-process
- streaming
- concurrent-output
- path
- optics
- generic-optics
- reflection

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  medlib:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - medlib
    - optparse-applicative
